### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by maelle** [ropensci/tic#313] opened 2022-02-14 10:20 UTC
Via https://ropensci.r-universe.dev/ui#builds we see https://github.com/r-universe/ropensci/runs/5133431014?check_suite_focus=true

```r
   Running 'testthat.R'
 ERROR
Running the tests in 'tests/testthat.R' failed.
Last 13 lines of output:
    7.   \-tic::use_ghactions_yml(tmpl_type, write = FALSE, quiet = TRUE)
    8.     \-usethis::use_build_ignore(c(".ccache", ".github"))
    9.       +-usethis::write_union(proj_path(".Rbuildignore"), files)
   10.       | \-usethis:::user_path_prep(path)
   11.       |   \-fs::path_expand(path)
   12.       \-usethis::proj_path(".Rbuildignore")
   13.         +-fs::path_norm(path(proj_get(), ..., ext = ext))
   14.         +-fs::path(proj_get(), ..., ext = ext)
   15.         \-usethis::proj_get()
   16.           \-usethis::proj_set(".")
   17.             \-usethis::ui_stop("Path {ui_path(path)} does not appear to be inside a project or package.")
```

**Comment by pat-s** [comment] 2022-02-18 08:27
Hmm, R CMD Check in the GHA of the tic repo does not show this issue. I've made some small fixes yesterday, maybe these helped?

The last run was 21h hours ago, when is the next one scheduled?

**Comment by maelle** [comment] 2022-02-18 10:38
The last commit was built (see commit status) but although there is a green check mark it it seems it failed? Cc @jeroen 

Commits are built hourly.

**Comment by maelle** [comment] 2022-03-07 09:50
For what it's worth, on Ubuntu I get a clean R CMD check but errors with `devtools::test()`.


```r
==> devtools::test()

ℹ Loading tic
ℹ Testing tic
✓ | F W S  OK | Context
✓ |         1 | base64                                     
✓ |         3 | ci                                         
✓ |        12 | deploy                                     
⠏ |         0 | test-integration-assign.R                  
✓ Loading tic stage configuration from tic.R
✓ |         2 | test-integration-assign.R [0.3s]           
⠏ |         0 | test-integration-early-failure.R           
✓ Loading tic stage configuration from tic.R
Running script: step_run_code(stop("oops"))
<error/rlang_error>
Error:
! oops
---
Backtrace:
  1. base::tryCatch(...)
 29. base::.handleSimpleError(...)
 30. rlang h(simpleError(msg, call))
 31. handlers[[1L]](cnd)
Error : A step failed in stage "script": script.
✓ |         2 | test-integration-early-failure.R [0.7s]    
⠏ |         0 | test-integration-git-commit-paths.R        ┌────────────────────────────────────────┐
│                                        │
│   integration test: git commit paths   │
│                                        │
└────────────────────────────────────────┘
cloning into '/tmp/Rtmp8F9HhW/ticpkg2b477bb87680pkg'...

x | 1       0 | test-integration-git-commit-paths.R
───────────────────────────────────────────────────────────
Error (test-integration-git-commit-paths.R:33:3): integration test: git commit paths
Error in `git2r::push(refspec = "refs/heads/master")`: Error in 'git2r_push': src refspec 'refs/heads/master' does not match any existing object

Backtrace:
 1. withr::with_dir(...)
      at test-integration-git-commit-paths.R:33:2
 3. git2r::push(refspec = "refs/heads/master")
      at test-integration-git-commit-paths.R:43:6
───────────────────────────────────────────────────────────
⠏ |         0 | test-integration-git-race-path-branch-orphan.R┌───────────────────────────────────────────────────┐
│                                                   │
│   integration test: git race path branch orphan   │
│                                                   │
└───────────────────────────────────────────────────┘
cloning into '/tmp/Rtmp8F9HhW/git-race-path-branch-orphan-2b4739cf8efb/package'...

x | 1       0 | test-integration-git-race-path-branch-orphan.R
───────────────────────────────────────────────────────────
Error (test-integration-git-race-path-branch-orphan.R:45:3): integration test: git race condition + path + branch + orphaning
Error in `git2r::push(refspec = "refs/heads/master")`: Error in 'git2r_push': src refspec 'refs/heads/master' does not match any existing object

Backtrace:
 1. withr::with_dir(...)
      at test-integration-git-race-path-branch-orphan.R:45:2
 3. git2r::push(refspec = "refs/heads/master")
      at test-integration-git-race-path-branch-orphan.R:55:6
───────────────────────────────────────────────────────────
⠏ |         0 | test-integration-git-race-path-branch.R    ┌────────────────────────────────────────────┐
│                                            │
│   integration test: git race path branch   │
│                                            │
└────────────────────────────────────────────┘
cloning into '/tmp/Rtmp8F9HhW/git-race-path-branch-2b47782025db/package'...

x | 1       0 | test-integration-git-race-path-branch.R
───────────────────────────────────────────────────────────
Error (test-integration-git-race-path-branch.R:46:3): integration test: git race condition with path and branch
Error in `git2r::push(refspec = "refs/heads/master")`: Error in 'git2r_push': src refspec 'refs/heads/master' does not match any existing object

Backtrace:
 1. withr::with_dir(...)
      at test-integration-git-race-path-branch.R:46:2
 3. git2r::push(refspec = "refs/heads/master")
      at test-integration-git-race-path-branch.R:56:6
───────────────────────────────────────────────────────────
⠏ |         0 | test-integration-git-race.R                ┌────────────────────────────────┐
│                                │
│   integration test: git race   │
│                                │
└────────────────────────────────┘
cloning into '/tmp/Rtmp8F9HhW/git-race-2b4759893836/package'...

x | 1       0 | test-integration-git-race.R
───────────────────────────────────────────────────────────
Error (test-integration-git-race.R:38:3): integration test: git race condition
Error in `git2r::push(refspec = "refs/heads/master")`: Error in 'git2r_push': src refspec 'refs/heads/master' does not match any existing object

Backtrace:
 1. withr::with_dir(...)
      at test-integration-git-race.R:38:2
 3. git2r::push(refspec = "refs/heads/master")
      at test-integration-git-race.R:46:6
───────────────────────────────────────────────────────────
⠏ |         0 | test-integration-git.R                     ┌───────────────────────────┐
│                           │
│   integration test: git   │
│                           │
└───────────────────────────┘
cloning into '/tmp/Rtmp8F9HhW/git-2b4712735250/package'...

Package: package
Title: What the Package Does (One Line, Title Case)
Version: 0.0.0.9000
Authors@R (parsed):
    * First Last <first.last@example.com> [aut, cre] (YOUR-ORCID-ID)
Description: What the package does (one paragraph).
License: `use_mit_license()`, `use_gpl3_license()` or friends to
    pick a license
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.2
x | 1       0 | test-integration-git.R [0.1s]              
───────────────────────────────────────────────────────────
Error (test-integration-git.R:32:3): integration test: git
Error in `git2r::push(refspec = "refs/heads/master")`: Error in 'git2r_push': src refspec 'refs/heads/master' does not match any existing object

Backtrace:
 1. withr::with_dir(...)
      at test-integration-git.R:32:2
 3. git2r::push(refspec = "refs/heads/master")
      at test-integration-git.R:40:6
───────────────────────────────────────────────────────────
⠏ |         0 | test-integration-package.R                 ┌───────────────────────────────────────┐
│                                       │
│   integration test: package failure   │
│                                       │
└───────────────────────────────────────┘

Package: ticpkg2b4743ba9261pkg
Title: What the Package Does (One Line, Title Case)
Version: 0.0.0.9000
Authors@R (parsed):
    * First Last <first.last@example.com> [aut, cre] (YOUR-ORCID-ID)
Description: What the package does (one paragraph).
License: GPL-2
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.2
✓ Loading tic stage configuration from tic.R
Running install: step_install_deps(repos = repo_default(), type = getOption("pkgType"), 
    dependencies = TRUE)
Skipping install: 
function() {
      !ci_is_interactive()
    }
<environment: 0x556c084565a0>
Running script: step_rcmdcheck(warnings_are_errors = NULL, notes_are_errors = NULL, 
    args = NULL, build_args = NULL, error_on = "warning", repos = repo_default(), 
    timeout = Inf, check_dir = "check")
── R CMD build ─────────────────────────────────────────────────────────────────
* checking for file ‘.../DESCRIPTION’ ... OK
* preparing ‘ticpkg2b4743ba9261pkg’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
Removed empty directory ‘ticpkg2b4743ba9261pkg/R’
* building ‘ticpkg2b4743ba9261pkg_0.0.0.9000.tar.gz’

── R CMD check ─────────────────────────────────────────────────────────────────
* using log directory ‘/tmp/Rtmp8F9HhW/ticpkg2b4743ba9261pkg/check/ticpkg2b4743ba9261pkg.Rcheck’
* using R version 4.1.0 (2021-05-18)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* using options ‘--no-manual --as-cran’
* checking for file ‘ticpkg2b4743ba9261pkg/DESCRIPTION’ ... OK
* this is package ‘ticpkg2b4743ba9261pkg’ version ‘0.0.0.9000’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking serialization versions ... OK
* checking whether package ‘ticpkg2b4743ba9261pkg’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking for future file timestamps ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking examples ... NONE
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘test.R’
 ERROR
Running the tests in ‘tests/test.R’ failed.
Complete output:
  > stop("Check failure!")
  Error: Check failure!
  Execution halted
* checking for non-standard things in the check directory ... OK
* checking for detritus in the temp directory ... OK
* DONE

Status: 1 ERROR
See
  ‘/tmp/Rtmp8F9HhW/ticpkg2b4743ba9261pkg/check/ticpkg2b4743ba9261pkg.Rcheck/00check.log’
for details.

── R CMD check results ─────────────────── ticpkg2b4743ba9261pkg 0.0.0.9000 ────
Duration: 3s

> checking tests ...
  See below...

── Test failures ───────────────────────────────────────────────────── test ────

> stop("Check failure!")
Error: Check failure!
Execution halted

1 error x | 0 warnings ✓ | 0 notes ✓
<error/rlang_error>
Error:
! Errors found in rcmdcheck::rcmdcheck().
---
Backtrace:
  1. base::tryCatch(...)
 28. base::.handleSimpleError(...)
 29. rlang h(simpleError(msg, call))
 30. handlers[[1L]](cnd)
Error : A step failed in stage "script": script.
✓ |         1 | test-integration-package.R [5.1s]          
⠏ |         0 | test-integration-package.R                 ┌───────────────────────────────┐
│                               │
│   integration test: package   │
│                               │
└───────────────────────────────┘

Package: ticpkg2b4771fd8aa3pkg
Title: What the Package Does (One Line, Title Case)
Version: 0.0.0.9000
Authors@R (parsed):
    * First Last <first.last@example.com> [aut, cre] (YOUR-ORCID-ID)
Description: What the package does (one paragraph).
License: GPL-2
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.2
✓ Loading tic stage configuration from tic.R
Running install: step_install_deps(repos = repo_default(), type = getOption("pkgType"), 
    dependencies = TRUE)
Skipping install: 
function() {
      !ci_is_interactive()
    }
<environment: 0x55a767f185a0>
Running script: step_rcmdcheck(warnings_are_errors = NULL, notes_are_errors = NULL, 
    args = NULL, build_args = NULL, error_on = "warning", repos = repo_default(), 
    timeout = Inf, check_dir = "check")
── R CMD build ─────────────────────────────────────────────────────────────────
* checking for file ‘.../DESCRIPTION’ ... OK
* preparing ‘ticpkg2b4771fd8aa3pkg’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
Removed empty directory ‘ticpkg2b4771fd8aa3pkg/R’
* building ‘ticpkg2b4771fd8aa3pkg_0.0.0.9000.tar.gz’

── R CMD check ─────────────────────────────────────────────────────────────────
* using log directory ‘/tmp/Rtmp8F9HhW/ticpkg2b4771fd8aa3pkg/check/ticpkg2b4771fd8aa3pkg.Rcheck’
* using R version 4.1.0 (2021-05-18)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* using options ‘--no-manual --as-cran’
* checking for file ‘ticpkg2b4771fd8aa3pkg/DESCRIPTION’ ... OK
* this is package ‘ticpkg2b4771fd8aa3pkg’ version ‘0.0.0.9000’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking serialization versions ... OK
* checking whether package ‘ticpkg2b4771fd8aa3pkg’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking for future file timestamps ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking examples ... NONE
* checking for non-standard things in the check directory ... OK
* checking for detritus in the temp directory ... OK
* DONE

Status: OK
── R CMD check results ─────────────────── ticpkg2b4771fd8aa3pkg 0.0.0.9000 ────
Duration: 3.2s

0 errors ✓ | 0 warnings ✓ | 0 notes ✓
✓ |         1 | test-integration-package.R [5.3s]          
✓ |         1 | macro                                      
x | 1       4 | print [0.8s]                               
───────────────────────────────────────────────────────────
Error (test-print.R:31:3): print stages
Error: Error evaluating the step argument of add_step(), expected an object of class TicStep.
Original error: tentative d'appliquer un objet qui n'est pas une fonction
Backtrace:
 1. tic::do_pkgdown()
      at test-print.R:31:2
 3. tic::add_step(...)
 4. base::tryCatch(...)
      at tic/R/dsl.R:56:2
 5. base tryCatchList(expr, classes, parentenv, handlers)
 6. base tryCatchOne(expr, names, parentenv, handlers[[1L]])
 7. value[[3L]](cond)
───────────────────────────────────────────────────────────
✓ |         4 | test-repo [6.0s]                           
✓ |         2 | test-stages.R                              
✓ |         6 | tasks-base                                 
✓ |         3 | update-yaml [0.4s]                         
✓ |         9 | test-utils.R                               

══ Results ════════════════════════════════════════════════
Duration: 19.4 s

[ FAIL 6 | WARN 0 | SKIP 0 | PASS 51 ]
```

**Comment by pat-s** [comment] 2022-03-07 14:56
Thanks! I could reproduce it locally and it was indeed an issue which only appears in a local test environment and not on CI.

It should be fixed by 27904e3ef05b774d5c21b02ed541ab295c25b1d5. Hopefully this also makes the r-universe builds happy again :)

**Comment by pat-s** [comment] 2022-03-07 16:53
> The error when building binaries on Windows/macOS seemed different,

Ah indeed, I was too quick probably. Looks like the error is triggered as the builders don't emulate a pkg environ which seems to be present in "normal" R CMD checks? I'll see if I can escape it somehow.

**Comment by maelle** [comment] 2022-03-07 16:55
> I'll see if I can escape it somehow.

The worst-case = no binaries built, not too critical (compared to not having docs, which would be really bad) so no pressure!

**Comment by pat-s** [comment] 2022-03-17 07:09
Finally 🎉

**Closed by pat-s** 2022-03-17 07:09 UTC
